# Generated by Django 5.1.6 on 2025-05-16 21:15

import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalattachment',
            name='file',
            field=models.FileField(upload_to=journal.models.user_directory_path, verbose_name='File'),
        ),
    ]
