# Generated by Django 5.1.6 on 2025-06-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_journalentry_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='suggested_mood',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('calm', 'Calm'), ('neutral', 'Neutral'), ('excited', 'Excited')], help_text='Mood suggested by AI analysis.', max_length=50, null=True, verbose_name='AI Suggested Mood'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='suggested_tags',
            field=models.TextField(blank=True, help_text='Comma-separated tag names suggested by AI. User accepts by selecting actual Tags.', null=True, verbose_name='AI Suggested Tags (Names)'),
        ),
    ]
