# Generated by Django 5.1.6 on 2025-06-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_journalentry_suggested_mood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='suggested_mood',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='suggested_tags',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('calm', 'Calm'), ('neutral', 'Neutral'), ('excited', 'Excited')], max_length=50, null=True, verbose_name='Mood'),
        ),
    ]
