# Generated by Django 5.1.6 on 2025-06-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_journalentry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalattachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('other', 'Other')], default='other', editable=False, max_length=10, verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='ai_mood_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='ai_mood_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='ai_quote_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='ai_quote_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='ai_tags_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='ai_tags_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
