# Generated by Django 5.1.6 on 2025-06-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_alter_journalattachment_file_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalattachment',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Journal Attachment', 'verbose_name_plural': 'Journal Attachments'},
        ),
    ]
