# Generated by Django 5.1.6 on 2025-06-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_alter_journalattachment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalattachment',
            options={'verbose_name': 'Journal Attachment', 'verbose_name_plural': 'Journal Attachments'},
        ),
    ]
