# Generated by Django 5.1.6 on 2025-05-18 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryAnalysis',
            fields=[
                ('journal_entry', models.OneToOneField(help_text='The journal entry this analysis pertains to.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ai_analysis', serialize=False, to='journal.journalentry')),
                ('sentiment_score', models.FloatField(blank=True, help_text='Overall sentiment score from -1.0 (negative) to 1.0 (positive).', null=True)),
                ('extracted_keywords', models.JSONField(blank=True, default=list, help_text='List of keywords or topics extracted from the entry.', null=True)),
                ('generated_summary', models.TextField(blank=True, help_text='AI-generated summary of the journal entry.', null=True)),
                ('analysis_timestamp', models.DateTimeField(auto_now=True, help_text='When this analysis was last generated or updated.')),
            ],
            options={
                'verbose_name': 'Journal Entry AI Analysis',
                'verbose_name_plural': 'Journal Entry AI Analyses',
            },
        ),
    ]
