# Generated by Django 5.1.6 on 2025-05-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_transfer_profile_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="User's date of birth. Handle with privacy in mind.", null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='show_email_publicly',
            field=models.BooleanField(default=False, help_text="If checked, the user's email (from CustomUser) will be visible on their public profile.", verbose_name='Show Email Publicly'),
        ),
    ]
