# Generated by Django 5.1.6 on 2025-06-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_change_token_key',
            field=models.CharField(blank=True, help_text='Token key sent to the pending new email for verification.', max_length=64, null=True, verbose_name='Email Change Token Key'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_change_token_key_created_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp for when the email change token key was generated.', null=True, verbose_name='Email Change Token Key Created At'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_new_email',
            field=models.EmailField(blank=True, help_text='Stores a new email address awaiting verification after a change request.', max_length=254, null=True, verbose_name='Pending New Email'),
        ),
    ]
